/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container': '#181924',
        'primary-container': '#b28cff',
        'primary-dim': '#8a4cfc',
        'surface-bright': '#2a2b3a',
        'surface-tint': '#bd9dff',
        'on-background': '#f1effd',
        'surface-container-low': '#12131d',
        'inverse-surface': '#fbf8ff',
        'outline': '#757480',
        'secondary-container': '#00687a',
        'on-primary-fixed': '#000000',
        'secondary-dim': '#40ceed',
        'background': '#0d0e17',
        'error-dim': '#d73357',
        'outline-variant': '#474752',
        'surface-container-highest': '#242532',
        'primary-fixed': '#b28cff',
        'inverse-primary': '#742fe5',
        'inverse-on-surface': '#54545f',
        'secondary': '#53ddfc',
        'primary-fixed-dim': '#a67aff',
        'surface': '#0d0e17',
        'on-surface': '#f1effd',
        'on-secondary-container': '#ecfaff',
        'on-primary': '#3c0089',
        'surface-dim': '#0d0e17',
        'tertiary-container': '#fd4490',
        'surface-container-high': '#1d1f2b',
        'error': '#ff6e84',
        'error-container': '#a70138',
        'on-error': '#490013',
        'on-tertiary': '#470021',
        'tertiary-fixed': '#ff8eb1',
        'primary': '#bd9dff',
        'on-surface-variant': '#abaab7',
        'tertiary': '#ff6a9f',
        'tertiary-dim': '#ff6a9f',
        'surface-variant': '#242532',
        'surface-container-lowest': '#000000',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['"Space Grotesk"', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
